# Generated by Django 6.0.1 on 2026-02-17 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CAR_MAKE', models.CharField(max_length=100)),
                ('CAR_MODEL', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIRST_NAME', models.CharField(max_length=100)),
                ('LAST_NAME', models.CharField(max_length=100)),
                ('Username', models.CharField(max_length=100)),
                ('Age', models.IntegerField()),
                ('Email', models.EmailField(max_length=254)),
                ('Phone_Number', models.IntegerField()),
                ('Driver_Status', models.BooleanField(default=False)),
                ('Verified_Status', models.BooleanField(default=False)),
                ('Rating', models.FloatField()),
            ],
        ),
    ]
