# Generated by Django 4.2.30 on 2026-04-22 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_school_alter_car_id_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.CharField(blank=True, choices=[('florida_southern', 'Florida Southern College'), ('ucf', 'University of Central Florida'), ('other', 'Other')], max_length=100, null=True),
        ),
    ]
