# Generated by Django 6.0.1 on 2026-02-19 21:43

import location_field.models.plain
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('city', models.CharField(max_length=200)),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
