# Generated by Django 6.0.1 on 2026-02-19 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
    ]
