# Generated by Django 6.0.1 on 2026-02-25 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0002_riderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='total_seats',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
