# Generated by Django 6.0.1 on 2026-02-26 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_city'),
        ('rides', '0003_ride_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='events.event'),
        ),
    ]
