# Generated by Django 6.0.1 on 2026-03-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0003_ride_total_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='category',
            field=models.CharField(choices=[('theme_park', 'Theme Park'), ('sports', 'Sports Game'), ('concert', 'Concert'), ('school', 'School'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
