# Generated by Django 4.2.30 on 2026-04-14 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rides', '0004_review'),
        ('rides', '0004_ride_category'),
    ]

    operations = [
    ]
