# Generated by Django 4.2.29 on 2026-04-23 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_id'),
        ('rides', '0006_alter_review_id_alter_ride_id_alter_riderequest_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rides', to='events.event'),
        ),
    ]
